default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eventapp_development
test:
  <<: *default
  database: eventapp_test

production:
  <<: *default
  database: eventapp_production
  username: eventapp
  password: <%= ENV['EVENTAPP_DATABASE_PASSWORD'] %>
