# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ada9c0991cdf204941558279a3589c1a3b16aa09ec93bd059e0cbaaf73b8efe189d81387d781d35c40bd830dd747d8bcd54809513169376d6f7d76062124e28

test:
  secret_key_base: d2cc928378b06de7cc44a8db00764323fffd5e0e2a076cab8d71e47876f206e6fcf6ee2a25fda6ac8b5fd2bce27b0c22cd405150e71ff3aecc2a59e20f4df89a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
